export const ID = 'ID'
export const ID_DETAIL = 'ID_DETAIL'
export const SEARCH_RESULT = 'SEARCH_RESULT'
export const SEARCH_RESULT_NULL = 'SEARCH_RESULT_NULL'
export const SEARCH_BRAND = 'SEARCH_BRAND'
export const CLICK_CATEGORY = 'CLICK_CATEGORY'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const TOGGLE_FORM = 'TOGGLE_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const OPEN_FORM = 'OPEN_FORM'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const GETPRODUCT_DATABASE = 'GETPRODUCT_DATABASE'
export const DELETE_CART = 'DELETE_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const TOTAL_PRICE = 'TOTAL_PRICE'
export const GETSTATE = 'GETSTATE'
export const BILL_ID = 'BILL_ID'
export const CART_ID = 'CART_ID'
export const UPIMG_ID = 'UPIMG_ID'
export const UPPRODUCT_ID = 'UPPRODUCT_ID'
export const LOAD_PRODUCT_LIST = 'LOAD_PRODUCT_LIST'
export const GETPRODUCT = 'GETPRODUCT'
export const API_NEWEE_5000 = 'https://api.newee.asia:5000'

//api
export const API_NEWEE_5001 = 'https://api.newee.asia:5001'

export const API_NEWEE_5001 = 'https://api.newee.asia:5001'

export const API_NEWEE_7001 = 'https://api.newee.asia:5001'

export const API_TEST = 'https://api.newee.asia:5001'
export const ADDTOCART = 'ADDTOCART'
export const REMOVETOCART = 'REMOVETOCART'
export const INCREASE_QUANTITY_SHOP = 'INCREASE_QUANTITY_SHOP'
export const DECREASE_QUANTITY_SHOP = 'DECREASE_QUANTITY_SHOP'
export const UPDATE_QUANTITY_SHOP = 'UPDATE_QUANTITY_SHOP'
export const GET_ALL_PRODUCT_SHOP = 'GET_ALL_PRODUCT_SHOP'
export const GET_NUMBER_CART_SHOP = 'GET_NUMBER_CART_SHOP'
export const ADD_CART_SHOP = 'ADD_CART_SHOP'
export const UPDATE_CART_SHOP = 'UPDATE_CART_SHOP'
export const DELETE_CART_SHOP = 'DELETE_CART_SHOP'
export const CLEAR_CART_SHOP = 'CLEAR_CART_SHOP'
export const LOAD_CART_LIST = 'LOAD_CART_LIST'
export const ID_PRODUCT = 'ID_PRODUCT'
export const CHOOSE_STEP_1 = 'CHOOSE_STEP_1'
export const CHOOSE_STEP_2 = 'CHOOSE_STEP_2'
export const CHOOSE_STEP_3 = 'CHOOSE_STEP_3'
export const CHOOSE_STEP_3_IMAGE = 'CHOOSE_STEP_3_IMAGE'
export const DATA_LOGIN = 'DATA_LOGIN'
export const NEWEE_LOGIN = 'NEWEE_LOGIN'
export const ALL_PRODUCT = 'ALL_PRODUCT'
export const BEST_PRODUCT = 'BEST_PRODUCT'
export const CK_PRODUCT = 'BEST_PRODUCT'
export const LOAD_ALL_PRODUCT_LIST = 'LOAD_ALL_PRODUCT_LIST'
export const LOAD_ALL_PRODUCT_SOCIAL = 'LOAD_ALL_PRODUCT_SOCIAL'
